spring.application.name=StudentManagement
spring.datasource.url=jdbc:mySql://localhost:3306/studentdatabase
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true